### PR TITLE
Add WARNING to BadgeVariant

### PR DESCRIPTION
**Pull request by Dudeplayz**

### CODE REVIEW

**Comment by mvysny** [comment]
Hi, thanks for the PR 👍 However, I do not see the `warning` style listed amongst the list of supported styles at https://vaadin.com/docs/v23/components/badge . Are you sure it's supported by Vaadin?

**Comment by Dudeplayz** [comment]
Hi @mvysny, yes it works fine, even with primary added. I think vaadin forgot to update the documentation after adding the warning styles. Are there any other places in karibu-tools/dsl that do not support the warning colors now?

**Comment by mvysny** [comment]
You're right, the "warning" theme variant indeed turns the badge yellow and seems to be working. I've asked the Vaadin guys whether this is officially supported; let's see what they tell us.

**Comment by mvysny** [comment]
Ah, I see you created a ticket already, excellent: https://github.com/vaadin/docs/issues/3898

I've got a reply from Vaadin designers that the "warning" theme variant is indeed officially supported. Thanks, excellent catch, merging the PR 👍

**Comment by Dudeplayz** [comment]
Thank you for your continued work on your libraries, I really love and appreciate them on a daily basis!

**Comment by mvysny** [comment]
Thank you, happy to hear such a positive feedback :)

**Pull request merged**
